<?php
if (!isset($_COOKIE['code'])) {
	//echo "No Cookie Set";
    return false;
} else {
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, "https://steemconnect.com/api/me");
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


	$headers = array();
	$headers[] = "Content-Type: application/json";
	$headers[] = "Authorization: " . $_COOKIE['code'];
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	$result = curl_exec($ch);
	if (curl_errno($ch)) {
		echo 'Error:' . curl_error($ch);
	}
	curl_close ($ch);
	$_result = json_decode($result);
	if(isset($_result->user)) {
        return $_result->user;
    } else {
		//echo "Something went wrong:<br />";
        return false;
    }
}